### ISSUE TITLE
Env variables substitution in services' URI in config file

### ISSUE THREAD

**Issue by Tony-Sol** [containers/podman-tui#438]
**Is your feature request related to a problem? Please describe.**
I want to make a distributable podman-tui config, which will relate to bundled env variables, but services' URI read from config file as is, so only full path required.
That's why it's not possible to replace this
```toml
[services]
  [services.localhost]
    default = true
    uri = "unix:///Users/tony/.local/share/containers/podman/machine/qemu/podman.sock"
```
with this
```toml
[services]
  [services.localhost]
    default = true
    uri = "unix://${XDG_DATA_HOME}/containers/podman/machine/qemu/podman.sock"
```

**Describe the solution you'd like**
Here https://github.com/containers/podman-tui/blob/bed5d263456f9556a36ed65a4712690edd8a57ea/config/read.go#L10-L27
add env variable substitution

**Additional context**
Nope
