### ISSUE TITLE
add macOS support

### ISSUE THREAD

**Issue by sanyer** [containers/podman-tui#72]
I was able to build it on macOS M1, but it is stuck on connecting to podman machine.

**Comment by sanyer** [comment]
Oh, it actually worked after I modified config file:

```toml
[services]

  [services.podman-machine-default]
    uri = "ssh://core@localhost:65360/run/user/501/podman/podman.sock"
    identity = "/Users/romanzhuzha/.ssh/podman-machine-default"
    default = true
```
